#docker-compose.yml
version: "3.3"
services:
  app:
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DB_USER: root
      DB_HOST: db
      DB_PASSWORD: root
    ports:
      - "8000:8000"
  db:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"

    
